name: Angular CI CD

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npx ng lint

      - name: Run Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular App
        run: npm run build -- --base-href /angular_cicd/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/angular_cicd/browser

      - name: Create Production Config
        run: cp src/config/config.prod.json src/config/config.json

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4